In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.decomposition import PCA


In [2]:
data=pd.read_csv(r"C:\Users\samir\Downloads\archive (1)\heart.csv")

In [3]:
data.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [5]:
data.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [6]:
data.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [16]:
features=data[['Age','RestingBP','Cholesterol','FastingBS','MaxHR','Oldpeak']]

In [18]:
features.head()

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
2   37        130          283          0     98      0.0
3   48        138          214          0    108      1.5
4   54        150          195          0    122      0.0
5   39        120          339          0    170      0.0
6   45        130          237          0    170      0.0

In [19]:
target=data[['HeartDisease']]

In [20]:
target.head()

HeartDisease
2             0
3             1
4             0
5             0
6             0

In [21]:
scaler=MinMaxScaler()
features_scal=scaler.fit_transform(features)
target_scal=scaler.fit_transform(target)


In [22]:
features_scal

array([[0.18367347, 0.65      , 0.46932007, 0.        , 0.26760563,
        0.29545455],
       [0.40816327, 0.69      , 0.35489221, 0.        , 0.33802817,
        0.46590909],
       [0.53061224, 0.75      , 0.32338308, 0.        , 0.43661972,
        0.29545455],
       ...,
       [0.59183673, 0.65      , 0.2172471 , 0.        , 0.38732394,
        0.43181818],
       [0.59183673, 0.65      , 0.39137645, 0.        , 0.8028169 ,
        0.29545455],
       [0.20408163, 0.69      , 0.29021559, 0.        , 0.79577465,
        0.29545455]])

In [26]:
# target_scal

In [28]:
X_train, X_test, y_train, y_test = train_test_split(features_scal,target_scal,test_size=0.3)

In [32]:
lr=cross_val_score(LogisticRegression(),features_scal,target_scal)

C:\Users\samir\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\samir\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\samir\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\samir\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

In [33]:
np.average(lr)

0.7314920408648136

In [35]:
svm=cross_val_score(SVC(),features_scal,target_scal)

C:\Users\samir\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\samir\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\samir\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\samir\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

In [36]:
np.average(svm)

0.736944642432882

In [37]:
rf=cross_val_score(RandomForestClassifier(),features_scal,target_scal)
np.average(rf)

C:\Users\samir\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\samir\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\samir\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\samir\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for

0.7282074126870991

In [40]:
pca=PCA(n_components=3)
pca_features=pca.fit_transform(features)

In [41]:
pca_features.shape

(916, 3)

In [42]:
pca_features

array([[ 81.99692656,  38.13980605,  16.14575363],
       [ 13.74286089,  28.68783302,   2.77391   ],
       [ -4.26334786,  18.10227519, -13.43613312],
       ...,
       [-68.91665468,  17.27964629,   5.34064477],
       [ 39.28009129, -33.64086504,  -6.27696739],
       [-21.36611441, -37.20495816, -13.71830646]])

In [43]:
sclr=MinMaxScaler()
pca_features_sclr=sclr.fit_transform(pca_features)

In [44]:
pca_features_sclr

array([[0.47009774, 0.71947878, 0.46979692],
       [0.3573611 , 0.65467191, 0.39928556],
       [0.32761988, 0.58209267, 0.31380802],
       ...,
       [0.22083068, 0.57645237, 0.41282026],
       [0.39954147, 0.22731899, 0.35155917],
       [0.29937089, 0.202882  , 0.31232008]])

In [46]:
 X_train, X_test, y_train, y_test = train_test_split(pca_features_sclr,target_scal,test_size=0.3)

In [51]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)


C:\Users\samir\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7054545454545454